<!DOCTYPE html> 
<html>
<style type="text/css">
	#link-read{
		text-decoration: none;
		font-style: italic;
	}
	#link-read:hover{
		color: blue;
	}
</style>
  <h3><b>DETAIL LAPORAN</b></h3>
  </br>
  <table>
  		<tr>
  			<td>NAMA LAPORAN</td>
  			<td>:</td>
  			<td><?php echo $this->data[0]['lap_name']?></td>
  		</tr>
  		<tr>
  			<td>BULAN</td>
  			<td>:</td>
  			<td><?php echo $this->data[0]['lap_bulan']?></td>
  		</tr>
  		<tr>
  			<td>TAHUN</td>
  			<td>:</td>
  			<td><?php echo $this->data[0]['lap_tahun']?></td>
  		</tr>
  		<tr>
  			<td>DETAIL</td>
  			<td>:</td>
  			<td><?php echo $this->data[0]['lap_detail']?></td>
  		</tr>
  </table>
  <a href="<?php echo $this->baseUrl();?>/laporan/">kembali</a>
</html>