<!DOCTYPE html> 
<html>
<style type="text/css">
	#link-read{
		text-decoration: none;
		font-style: italic;
	}
	#link-read:hover{
		color: blue;
	}
  table{
    font-size: 15px;
  }
  tr{
    width: 100%;
  }
  #kembali{
    display: inline-block;
  }
  #kembali a{
    padding-left: 5px;
    float: left;
  }
  #kembali img{
    float: left;
  }
</style>
  <h3><b>DETAIL LAPORAN</b></h3>
  </br>
  <table>
  		<tr>
  			<td width="120px">Nama Laporan</td>
  			<td>:</td>
  			<td><?php echo $this->data[0]['lap_name']?></td>
  		</tr>
  		<tr>
  			<td width="120px">Bulan</td>
  			<td>:</td>
  			<td><?php echo $this->data[0]['lap_bulan']?></td>
  		</tr>
  		<tr>
  			<td width="120px">Tahun</td>
  			<td>:</td>
  			<td><?php echo $this->data[0]['lap_tahun']?></td>
  		</tr>
  		<tr>
  			<td width="120px"><p>Detail</p></td>
  			<td><p>:</p></td>
  			<td></td>
  		</tr>
      <tr>
        <td colspan="3"><?php echo $this->data[0]['lap_detail']?></td>
      </tr>
  </table>
  <div id="kembali">
    <img src="<?php echo $this->baseUrl();?>/images/left-icon.png"><a href="<?php echo $this->baseUrl();?>/laporan/">kembali</a>
  </div>
</html>