<!DOCTYPE html> 
<html>
<style type="text/css">
	#link-read{
		text-decoration: none;
		font-style: italic;
	}
	#link-read:hover{
		color: blue;
	}
  td, th{
    width: 20%;
    font-size: 18px;
  }
  td a{
    text-decoration: none;
    font-weight: 200;
    font-size: 16px;

  }
  thead tr{
    background-color: grey;
  }
  table{
    border: 1px solid black;
  }
  tbody td{
    text-align: center;
  }
</style>
  <h3><b>AGENDA WARGA ALAM CITRA</b></h3>
  </br>
  <table>
	 <thead>
	 	<tr>
	 		<th>Nama Laporan</th>
	 		<th>Bulan</th>
      <th>Tahun</th>
	 		<th>Aksi</th>
	 	</tr>
	 </thead>
 	 <tbody>
  		<?php for($a=0;$a<count($this->data);$a++){
  			$b=$a+1;
  		?>
  		<tr>
  			<td><?php echo $this->data[$a]['lap_name']?></td>
  			<td><?php echo $this->data[$a]['lap_bulan']?></td>
  			<td><?php echo $this->data[$a]['lap_tahun']?></td>
  			<td><a href="<?php echo $this->baseUrl();?>/laporan/detail/p/<?php echo $this->data[$a]['lap_id']?>">detail</a></td>
  		</tr>
  		<?php }?>
  		</tbody>
  </table>
</html>