<!DOCTYPE html> 
<html>
  <style type="text/css">
    #konten-kontak{
      width: 100%;
      display: inline-block;
    }
    #konten-kontak #kontak-kiri{
      width: 100%;
      float: left;
    }
    #konten-kontak #kontak-kiri #alamat{
      display: inline-block;
      float: left;
      width: 70%;
      padding-left: 1%;
    }
    #konten-kontak #kontak-kanan{
      width: 100%;
      float: left;
      padding: 15px;
    }

  </style>
  <h1>Contact Us</h1>
  <div id="konten-kontak">
    <div id="kontak-kiri">
      <img src="<?php echo $this->baseUrl();?>/images/logo2.jpg" width="200px" height="200px" style="float:left;">
      <div id="alamat">
        <h2 style="font-size: 21px;font-weight:600;">PAGUYUBAN WARGA ALAM CITRA</h2>
        <p style="font-size: 17px;">Perumahan Alam Citra RT 07 dan 08
          <br/>Dk. Cabeyan, Kel. Panggungharjo, Kec. Sewon<br/> Kab. Bantul, DIY 55188
        </p>
      </div>
    </div>
    <div id="kontak-kanan">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3952.3419550395165!2d110.35433077129167!3d-7.859236050303502!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a56154b062dc3%3A0xd3ca4f5d3d421590!2sAlam+Citra!5e0!3m2!1sen!2sid!4v1427979908329" width="600" height="450" frameborder="0" style="border:0"></iframe>
    </div>
  </div> 
  
</html>