<!DOCTYPE html> 
<html>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/prettyPhoto.css" />
<style>
.photoGrid { padding: 6px; /* Spacing arround grid */ }

.photoGrid .item {
  float: left;
  margin: 2px; /* Spacing between images */
}

.photoGrid .item img {
  width: 100%;
  max-width: 100%;
  max-height: 100%;
}
</style>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> 
<script src="<?php echo $this->baseUrl();?>/js/jquery.prettyPhoto.js"></script> 
<script src="<?php echo $this->baseUrl();?>/js/jquery.photogrid.js"></script> 
<script>
$(function() {

  var defaults = {
    itemSelector: ".item", // item selecor ;-)
    resize: true, // automatic reload grid on window size change
    rowHeight: $(window).height() / 2, // looks best, but needs highres thumbs
    callback: function() {} // fires when layouting grid is done
  };


  $(window).load(function() { // or use https://github.com/desandro/imagesloaded
    $('.photoGrid').photoGrid({
      rowHeight: "150"
    });
  });
  
});
</script>
<script type="text/javascript" charset="utf-8">
      $(document).ready(function(){
        $("area[rel^='prettyPhoto']").prettyPhoto();
        
        $(".gallery:first a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'normal',theme:'light_square',slideshow:3000, autoplay_slideshow: false});
        $(".gallery:gt(0) a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast',slideshow:10000, hideflash: true});
    
        $("#custom_content a[rel^='prettyPhoto']:first").prettyPhoto({
          custom_markup: '<div id="map_canvas" style="width:260px; height:265px"></div>',
          changepicturecallback: function(){ initialize(); }
        });

        $("#custom_content a[rel^='prettyPhoto']:last").prettyPhoto({
          custom_markup: '<div id="bsap_1259344" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div><div id="bsap_1237859" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6" style="height:260px"></div><div id="bsap_1251710" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div>',
          changepicturecallback: function(){ _bsap.exec(); }
        });
      });
      </script>
<h1>Galery Photo</h1>
<div class="photoGrid clearfix gallery"> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra.jpg" alt="alam1"></a> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra1.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra1.jpg" alt="alam2"></a> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra2.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra2.jpg" alt="alam3"></a> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra3.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra3.jpg" alt="alam4"></a> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra4.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra4.jpg" alt="alam5"></a> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra5.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra5.jpg" alt="alam6"></a> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra6.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra6.jpg" alt="alam7"></a> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra7.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra7.jpg" alt="alam8"></a> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra8.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra8.jpg" alt="alam9"></a> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra9.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra9.jpg" alt="alam10"></a> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra10.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra10.jpg" alt="alam11"></a> 
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra11.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra11.jpg" alt="alam12"></a>
  <a class="item" href="<?php echo $this->baseUrl();?>/images/alamcitra12.jpg" rel="prettyPhoto[gallery1]"><img src="<?php echo $this->baseUrl();?>/images/alamcitra12.jpg" alt="alam13"></a>
</div>

</html>