<!DOCTYPE html> 
<html>
<style type="text/css">
	#link-read{
		text-decoration: none;
		font-style: italic;
	}
	#link-read:hover{
		color: blue;
	}
  .framming{
    width: 200px;
    height: 150px;
    border: 1px solid black;
    overflow: hidden;
    float: left;
    margin-right: 10px;
    margin-bottom: 3px;
  }
  .framming img{
    width: 350px;
    height: 250px;
   margin: -75px 0 0 -100px;
 }
 .new{
  width: 100%;
  display: inline-block;
  margin-top: 20px;
 }
 .detail-berita{
  display: inline-block;
  margin-right: 5px;
 }
</style>
<?php
foreach ($this->data as $data) { ?>


<div class="new">
  <h1><?php echo $data['news_title'];?></h1>
  <div class="framming">
    <img src="<?php echo $this->baseUrl();?>/img/<?php echo $data['news_image'];?>">
  </div> 
  <?php 

  $a = $data['news_detail'];

  	$b = substr($a, 0, 500);
  	$c = substr($b, 0, strrpos($b, ' '));
  echo '<div class="detail-berita">'.$c.'</div>';
  ?>
  <br/><span><a id="link-read" href="#">read more</a></span>
</div>
<?php
  }
?>
 
</html>