<!DOCTYPE html> 
<html>

<head>
  <title>Paguyuban Warga Alam Citra</title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/style.css" />
  <!-- modernizr enables HTML5 elements and feature detects -->
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/modernizr-1.5.min.js"></script>
</head>

<body>
  <div id="main">		

    <header>
	  <nav>
		<div id="menubar">
          <ul id="nav">
            <li class="current"><a href="<?php echo $this->baseUrl();?>">Home</a></li>
            <li><a href="ourwork.html">Our Work</a></li>
            <li><a href="testimonials.html">Testimonials</a></li>
            <li><a href="projects.html">Projects</a></li>
            <li><a href="contact.html">Contact Us</a></li>
          </ul>
		</div><!--close menubar-->	
      </nav>
	  <div id="strapline">
	    <div id="welcome_slogan">
	      <h3>Paguyuban Warga Alam Citra</h3>
	    </div><!--close welcome_slogan-->
      </div><!--close strapline-->    
	</header>
  
  <div class="slideshow">
   <ul class="slideshow">
    <li class="show"><img width="1100" height="300" src="<?php echo $this->baseUrl();?>/images/alamcitra.jpg" alt="Perumahan Alam Citra" /></li>
    <li><img width="1100" height="300" src="<?php echo $this->baseUrl();?>/images/alamcitra1.jpg" alt="Tampak Depan Perumahan Alam Citra" /></li>
   </ul> 
  </div>

	<div id="site_content">		
	  
   <div class="sidebar_container">       
    <div class="sidebar">
      <div class="sidebar_item">
        <h2>News Update</h2>
        <a href="#">Jadwal Ronda Mingguan</a>
        <a href="#">Jadwal Arisan Mingguan</a>
        <a href="#">Jadwal Kerja Bakti Mingguan</a>
        <a href="#">Jadwal Kumpul Mingguan</a>
      </div><!--close sidebar_item--> 
    </div><!--close sidebar-->     		
    <div class="sidebar">
      <div class="sidebar_item">
        <h2>Iklan</h2>
        <!-- <h3>February 2013</h3> -->
        <a href="#">Jual Rumah Tipe 42</a>      
        <a href="#">Jual Rumah Tipe 43 [Sold Out]</a>      
        <a href="#">Rumah dikontrakan Tipe 50</a>         
      </div><!--close sidebar_item--> 
    </div><!--close sidebar-->		

  </div><!--close sidebar_container-->	

  
	   
	  <div id="content">
        <div class="content_item">
		  <h1>Welcome To Our Website</h1> 
    <p>This standards compliant, simple, fixed width website template is released as an 'open source' design (under the Creative Commons Attribution 3.0 Licence), which means that you are free to download and use it for anything you want (including modifying and amending it). If you wish to remove the &ldquo;website template by Free HTML5 Templates&rdquo;, all I ask is for a donation of &pound;20.00 GBP. Please feel free to contact me with any questions you may have about my free HTML5 website templates or bespoke work.</p>   		
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi elit sapien, tempus sit amet hendrerit volutpat, euismod vitae risus. Etiam consequat, sem et vulputate dapibus, diam enim tristique est, vitae porta eros mauris ut orci. Praesent sed velit odio. Ut massa arcu, suscipit viverra molestie at, aliquet a metus. Nullam sit amet tellus dui, ut tincidunt justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis egestas laoreet. Nunc non ipsum metus, non laoreet urna. Vestibulum quis risus quis diam mattis tempus. Vestibulum suscipit pretium tempor. </p>	 
		</div><!--close content_item-->
      </div><!--close content-->   
	</div><!--close site_content-->  	

    <footer>
	  <!-- <a href="index.html">Home</a> | <a href="ourwork.html">Our Work</a> | <a href="testimonials.html">Testimonials</a> | <a href="projects.html">Projects</a> | <a href="contact.html">Contact</a><br/><br/>
	  <a href="http://fotogrph.com">Images</a> | Heart Internet <a href="http://www.heartinternet.co.uk/web-hosting/">web hosting</a> | website template by <a href="http://www.freehtml5templates.co.uk">Free HTML5 Templates</a> -->
    <p>&copy; Alam Citra 2015</p>
    </footer>
	
  </div><!--close main-->
  
  <!-- javascript at the bottom for fast page loading -->
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/image_slide.js"></script>
  
</body>
</html>