<!DOCTYPE html> 
<html>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
  
  //how much items per page to show
  var show_per_page = 5; 
  //getting the amount of elements inside content div
  var number_of_items = $('#content').children().find('div.new').size();
  //alert(number_of_items);
  //calculate the number of pages we are going to have
  var number_of_pages = Math.ceil(number_of_items/show_per_page);
  
  //set the value of our hidden input fields
  $('#current_page').val(0);
  $('#show_per_page').val(show_per_page);
  
  //now when we got all we need for the navigation let's make it '
  
  /* 
  what are we going to have in the navigation?
    - link to previous page
    - links to specific pages
    - link to next page
  */
  var navigation_html = '<a class="previous_link" href="javascript:previous();">Prev</a>';
  var current_link = 0;
  while(number_of_pages > current_link){
    navigation_html += '<a class="page_link" href="javascript:go_to_page(' + current_link +')" longdesc="' + current_link +'">'+ (current_link + 1) +'</a>';
    current_link++;
  }
  navigation_html += '<a class="next_link" href="javascript:next();">Next</a>';
  
  $('#page_navigation').html(navigation_html);
  
  //add active_page class to the first page link
  $('#page_navigation .page_link:first').addClass('active_page');
  
  //hide all the elements inside content div
  $('#content').children().find('div.new').css('display', 'none');
  
  //and show the first n (show_per_page) elements
  $('#content').children().find('div.new').slice(0, show_per_page).css('display', 'inline-block');
  
});

function previous(){
  
  new_page = parseInt($('#current_page').val()) - 1;
  //if there is an item before the current active link run the function
  if($('.active_page').prev('.page_link').length==true){
    go_to_page(new_page);
  }
  
}

function next(){
  new_page = parseInt($('#current_page').val()) + 1;
  //if there is an item after the current active link run the function
  if($('.active_page').next('.page_link').length==true){
    go_to_page(new_page);
  }
  
}
function go_to_page(page_num){
  //get the number of items shown per page
  var show_per_page = parseInt($('#show_per_page').val());
  
  //get the element number where to start the slice from
  start_from = page_num * show_per_page;
  
  //get the element number where to end the slice
  end_on = start_from + show_per_page;
  
  //hide all children elements of content div, get specific items and show them
  $('#content').children().find('div.new').css('display', 'none').slice(start_from, end_on).css('display', 'inline-block');
  
  /*get the page link that has longdesc attribute of the current page and add active_page class to it
  and remove that class from previously active page link*/
  $('.page_link[longdesc=' + page_num +']').addClass('active_page').siblings('.active_page').removeClass('active_page');
  
  //update the current page input field
  $('#current_page').val(page_num);
}
  
</script>
<style type="text/css">
#page_navigation a{
  padding:3px;
  border:1px solid gray;
  margin:2px;
  color:black;
  text-decoration:none
}
.active_page{
  background:darkblue;
  color:white !important;
}
	#link-read{
		text-decoration: none;
		font-style: italic;
	}
	#link-read:hover{
		color: blue;
	}
  .framming{
    width: 200px;
    height: 150px;
    border: 1px solid black;
    overflow: hidden;
    float: left;
    margin-right: 10px;
    margin-bottom: 3px;
  }
  .framming img{
    width: 350px;
    height: 250px;
   margin: -75px 0 0 -100px;
 }
 .new{
  width: 100%;
  display: inline-block;
  margin-top: 20px;
 }
 #content{
  display: inline-block;
  margin-right: 5px;
 }
 #page_navigation{
  margin-left: 40%;
 }
</style>
<input type='hidden' id='current_page' />
<input type='hidden' id='show_per_page' />
<div id='content'>
  <?php
foreach ($this->data as $data) { ?>


<div class="new">
  <h1><?php echo $data['news_title'];?></h1>
  <div class="framming">
    <img src="<?php echo $this->baseUrl();?>/img/news/<?php echo $data['news_image'];?>">
  </div> 
  <?php 

  $a = $data['news_detail'];

    $b = substr($a, 0, 500);
    $c = substr($b, 0, strrpos($b, ' '));
  echo $c;
  ?>
  <br/><span><a id="link-read" href="#">read more</a></span>
</div>
<?php
  }
?>
</div>
<div id='page_navigation'></div> 

 
</html>