<!DOCTYPE html> 
<html>
<style type="text/css">
  #link-read{
    text-decoration: none;
    font-style: italic;
  }
  #link-read:hover{
    color: blue;
  }
  .framming{
    max-width: 700px;
    max-height: 400px;
    overflow: hidden;
    float: left;
    margin-right: 10px;
    margin-bottom: 3px;
  }
  .framming img{
    width: 100%;
   /*margin: -75px 0 0 -100px;*/
 }
 .new{
  width: 100%;
  display: inline-block;
  margin-top: 20px;
 }
</style>
<div class="new">
  <h1>News 1</h1>
  <div class="framming">
    <img src="<?php echo $this->baseUrl();?>/images/alamcitra.jpg?>">
  </div> 
  <?php 
  $a = '<p>This standards compliant, simple, fixed width website template is released as an open source design (under the Creative Commons Attribution 3.0 Licence), which means that you are free to download and use it for anything you want (including modifying and amending it). If you wish to remove the &ldquo;website template by Free HTML5 Templates&rdquo;, all I ask is for a donation of &pound;20.00 GBP. Please feel free to contact me with any questions you may have about my free HTML5 website templates or bespoke work.</p>       
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi elit sapien, tempus sit amet hendrerit volutpat, euismod vitae risus. Etiam consequat, sem et vulputate dapibus, diam enim tristique est, vitae porta eros mauris ut orci. Praesent sed velit odio. Ut massa arcu, suscipit viverra molestie at, aliquet a metus. Nullam sit amet tellus dui, ut tincidunt justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis egestas laoreet. Nunc non ipsum metus, non laoreet urna. Vestibulum quis risus quis diam mattis tempus. Vestibulum suscipit pretium tempor. </p>';

    echo $a;
  ?>
</div>
</html>