f<html>
<script type="text/javascript">
$(function() {
    $( "#tgl-agenda" ).datepicker({ dateFormat: 'yy-mm-dd' }).val();
});
</script>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i><b>EDIT LAPORAN</b></center></div>
</br>
<form class="form-horizontal" role="form" method="post" autocomplete="off" enctype="multipart/form-data">
	<?php 
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php 
		}
	?>
	<?php 
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php 
		}
	?>
<div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
  <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Nama Laporan</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="nama" name="nama" value="<?php echo $this->det[0]['lap_name'];?>">
	      <input type="hidden" class="form-control" id="id" name="id" value="<?php echo $this->det[0]['lap_id'];?>">
	    </div>
  </div>
   <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Bulan</label>
	    <div class="col-sm-10">
	     <select class="form-control" id="bulan" name="bulan">
	    	<option value="null">Pilih</option>
	    	<option value="Januari" <?php if($this->det[0]['lap_bulan']=="Januari"){ ?> selected <?php } ?>>Januari</option>
	    	<option value="Februari" <?php if($this->det[0]['lap_bulan']=="Februari"){ ?> selected <?php } ?>>Februari</option>
	    	<option value="Maret" <?php if($this->det[0]['lap_bulan']=="Maret"){ ?> selected <?php } ?>>Maret</option>
	    	<option value="April" <?php if($this->det[0]['lap_bulan']=="April"){ ?> selected <?php } ?>>April</option>
	    	<option value="Mei" <?php if($this->det[0]['lap_bulan']=="Mei"){ ?> selected <?php } ?>>Mei</option>
	    	<option value="Juni" <?php if($this->det[0]['lap_bulan']=="Juni"){ ?> selected <?php } ?>>Juni</option>
	    	<option value="Juli" <?php if($this->det[0]['lap_bulan']=="Juli"){ ?> selected <?php } ?>>Juli</option>
	    	<option value="Agustus" <?php if($this->det[0]['lap_bulan']=="Agustus"){ ?> selected <?php } ?>>Agustus</option>
	    	<option value="September" <?php if($this->det[0]['lap_bulan']=="September"){ ?> selected <?php } ?>>September</option>
	    	<option value="Oktober" <?php if($this->det[0]['lap_bulan']=="Oktober"){ ?> selected <?php } ?>>Oktober</option>
	    	<option value="November" <?php if($this->det[0]['lap_bulan']=="November"){ ?> selected <?php } ?>>November</option>
	    	<option value="Desember" <?php if($this->det[0]['lap_bulan']=="Desember"){ ?> selected <?php } ?>>Desember</option>
	    </select>
	    </div>
  </div>
   <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Tahun</label>
	    <div class="col-sm-10">
	     <select class="form-control" id="tahun" name="tahun">
	    <?php for($i=2015;$i<=2060;$i++){?>
	      	<option <?php if($this->det[0]['lap_tahun']==$i){ ?> selected <?php } ?>  value="<?php echo $i;?>"><?php echo $i;?></option>
	      <?php }?>
	      </select>
	    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">laporan Detail</label>
     <div class="col-sm-10">
     	<textarea id="tos" name="tos"><?php echo $this->det[0]['lap_detail'];?></textarea>
						<script type="text/javascript">
							CKEDITOR.replace( 'tos',  {
	allowedContent: true
} );
						</script>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Save</button>
       <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/laporan/index'">Cancel</button>
    </div>
  </div>
</div>
</form>
</div>
</html>