<html>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i><b>ADD NEW ADMIN</b></center></div>
</br>
<form class="form-horizontal" role="form" method="post" autocomplete="off">
	<?php 
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php 
		}
	?>
	<?php 
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php 
		}
	?>
<div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
  <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Firstname</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="nama" name="nama">
	    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Lastname</label>
    <div class="col-sm-10">
     	<input type="text" class="form-control" id="lastname" name="lastname">
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
     	<input type="text" class="form-control" id="email" name="email">
    </div>
  </div>
  <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Akses</label>
	    <div class="col-sm-10">
	     <select name="akses">
		  <option value="admin" >Admin</option>
		  <option value="staff" >Staff</option>
		  <option value="merchant" >Merchant</option>
		</select>
	    </div>
  	</div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
     	<input type="text" class="form-control" id="password" name="password">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Save</button>
       <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/admin/index'">Cancel</button>
    </div>
  </div>
</div>
</form>
</div>
</html>