<html>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i><b>EDIT IKLAN DETAIL</b></center></div>
</br>
<form class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
<?php 
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php 
		}
	?>
	<?php 
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php 
		}
	?>
	<div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
	<div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Iklan Title</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="nama" name="nama" value="<?php echo $this->det[0]['iklan_name'];?>">
	      <input type="hidden" class="form-control" id="id" name="id" value="<?php echo $this->det[0]['iklan_id'];?>">
	    </div>
  	</div>
  	<div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Iklan Image</label>
    <div class="col-sm-10">
    		<input type="file" name="file" id="file">
    		<p class="help-block">Add image here.</p>
    		<input type="hidden" class="form-control" id="image" name="image" value="<?php echo $this->det[0]['iklan_image'];?>">
    </div>
   </div>
  	<div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Iklan Detail</label>
    <div class="col-sm-10">
     <textarea id="tos" name="tos"><?php echo $this->det[0]['iklan_detail'];?></textarea>
						<script type="text/javascript">
							CKEDITOR.replace( 'tos',  {
	allowedContent: true
} );
						</script>
    </div>
  </div>
  <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Iklan Owner</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="owner" name="owner" value='<?php echo $this->det[0]['iklan_owner'];?>'>
	    </div>
  </div>
   <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Contact Person</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="cp" name="cp" value="<?php echo $this->det[0]['cp'];?>">
	    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Iklan Status</label>
    <div class="col-sm-10">
    		<select id="status" name="status" class="form-control">
         	  <option value="0">Choose</option>
			  <option value="1" <?php if ($this->det[0]['iklan_status']=='1'){?>selected<?php }?>>Aktif</option>
			  <option value="0" <?php if ($this->det[0]['iklan_status']=='0'){?>selected<?php }?>>Non Aktif</option>
			</select>
    </div>
  </div>
  	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
	       <button type="submit" class="btn btn-default">Save</button>
	       <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/admin/index'">Cancel</button>
	    </div>
  	</div>
</div>
</form>
</div>
</html>