<!DOCTYPE html> 
<html>
<style type="text/css">
	#link-read{
		text-decoration: none;
		font-style: italic;
	}
	#link-read:hover{
		color: blue;
	}
  #kembali{
    display: inline-block;
  }
  #kembali a{
    padding-left: 5px;
    float: left;
  }
  #kembali img{
    float: left;
  }
</style>
  <h3><b>DETAIL ACARA</b></h3>
  </br>
  <table>
  		<tr>
  			<td width="120px">Acara</td>
  			<td>: </td>
  			<td> <?php echo $this->data[0]['agenda_name']?></td>
  		</tr>
  		<tr>
  			<td width="120px">Tanggal Acara</td>
  			<td>: </td>
  			<td> <?php echo $this->data[0]['agenda_date']?></td>
  		</tr>
  		<tr>
  			<td width="120px">Tempat Acara</td>
  			<td>: </td>
  			<td> <?php echo $this->data[0]['agenda_place']?></td>
  		</tr>
  		<tr>
  			<td width="120px">Detail Acara</td>
  			<td>: </td>
  			<td></td>
  		</tr>
      <tr>
        <td colspan="3"><?php echo $this->data[0]['agenda_detail']?></td>
      </tr>
  </table>
  <div id="kembali">
    <img src="<?php echo $this->baseUrl();?>/images/left-icon.png"><a href="<?php echo $this->baseUrl();?>/agenda/" style>kembali</a>
  </div>
</html>