<!DOCTYPE html> 
<html>
<style type="text/css">
	#link-read{
		text-decoration: none;
		font-style: italic;
	}
	#link-read:hover{
		color: blue;
	}
</style>
  <h3><b>DETAIL ACARA</b></h3>
  </br>
  <table>
  		<tr>
  			<td>ACARA</td>
  			<td>:</td>
  			<td><?php echo $this->data[0]['agenda_name']?></td>
  		</tr>
  		<tr>
  			<td>TANGGAL ACARA</td>
  			<td>:</td>
  			<td><?php echo $this->data[0]['agenda_date']?></td>
  		</tr>
  		<tr>
  			<td>TEMPAT ACARA</td>
  			<td>:</td>
  			<td><?php echo $this->data[0]['agenda_place']?></td>
  		</tr>
  		<tr>
  			<td>DETAIL ACARA</td>
  			<td>:</td>
  			<td><?php echo $this->data[0]['agenda_detail']?></td>
  		</tr>
  </table>
  <a href="<?php echo $this->baseUrl();?>/agenda/">kembali</a>
</html>