<!DOCTYPE html> 
<html>
<style type="text/css">
	#link-read{
		text-decoration: none;
		font-style: italic;
	}
	#link-read:hover{
		color: blue;
	}
</style>
  <h3><b>AGENDA WARGA ALAM CITRA</b></h3>
  </br>
  <table>
  		<?php for($a=0;$a<count($this->data);$a++){
  			$b=$a+1;
  		?>
  		
  		<tr>
  			<td><?php echo $this->data[$a]['agenda_name']?></td>
  			<td><?php echo $this->data[$a]['agenda_date']?></td>
  			<td><a href="<?php echo $this->baseUrl();?>/agenda/detail/p/<?php echo $this->data[$a]['agenda_id']?>">detail</a></td>
  		</tr>
  		
  		<?php }?>
  </table>
</html>