<html>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.js"></script>
<script type="text/javascript">

	$(function() {
		$("table").tablesorter({debug: true})
		$("a.append").click(appendData);


	});

</script>
	<body>
	<?php 
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php 
		}
	?>
		<div class="panel panel-info">
		<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i>&nbsp;<b>LIST NEWS</b>
			<div class="col-lg-6" style="float:right;position: relative;left: 30px;bottom: 6px;">
				<div class="input-group">
					<div class="input-group-btn">
					<form method="post">
						<div style="width:165px;background: url('../img/blue_down.png') no-repeat scroll 96% 50% #FFF;overflow: hidden;margin-right:3px;">
							<select class="form-control" id="sel1" style="width: 190px;margin-right: 1px;background: none repeat scroll 0% 0% transparent;" name="kategori">
								<option value='all'>All</option>
								<option value='headline'>Headline</option>
							</select>
						</div>
					</div><!-- /btn-group -->
					<input type="text" class="form-control" placeholder="Search for..." style="width: 70%;" name="key">
					<span class="input-group-btn">
						<button class="btn btn-default" type="submit" style="
						position: relative;
						right: 118px;
						">Go!</button>
					</span>
					</form>
				</div><!-- /input-group -->
			</div>
		</div>
		<table class="table">
		        <thead>
		          <tr align="center">
		          	<th width="100">No</th>
		            <th>Headline</th>
		            <th>Date Created</th>
		            <th colspan="2">Action</th>
		          </tr>
		        </thead>
		        <tbody>
		         <?php for($a=0;$a < count($this->detail);$a++){
		         	$b = $a+1;
		         		?>
		         <tr>
		         	<td><?php echo $b;?></td>
		         	<td><?php echo $this->detail[$a]['news_title'];?></td>
		         	<td><?php echo $this->detail[$a]['news_date_created'];?></td>
		         	<td width="50px"><a class="btn btn-default btn-lg active" href="<?php echo $this->baseUrl();?>/admin/news/edit/p/<?php echo $this->detail[$a]['news_id']?>" style="cursor: pointer;"><span class="glyphicon glyphicon-edit">Edit</span></a></td>
		         	<td width="50px"> <a class="btn btn-default btn-lg active" style="cursor: pointer;" onclick="hps('<?php echo $this->detail[$a]['news_id']?>')"><span class="glyphicon glyphicon-remove-circle">Delete</span></a></td>
		         </tr>
		         <?php }?>
		        </tbody>
		        <tfoot>
		        </tfoot>
		      </table>
		      
		      </form>
		</div>
		
		<script>
		          
		function hps(id){
			$.post('<?php echo $this->baseUrl()."/admin/admin/delete/id"?>',{key: id}, function(data){
		          if(data.edit==true) {
					alert('Data Clear');
					parent.location.href = "<?php echo $this->baseUrl()?>/admin/admin/index";
			      } else {
			    	  alert('Failed Clear Data');  
			      }
		      });
			
		}
		</script>
	</body>
</html>