<!DOCTYPE html> 
<html>

<head>
  <title>Paguyuban Warga Alam Citra</title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/style.css" />
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.min.js"></script>
  <!-- modernizr enables HTML5 elements and feature detects -->
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/modernizr-1.5.min.js"></script>

</head>

<body>
  <div id="main">   

    <header>
    <div id="strapline">
     <div id="welcome_slogan">
       <img width="50px" height="50px" src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Perumahan Alam Citra" />
       <h3>Paguyuban Warga Alam Citra</h3>
       <!-- <img width="50px" height="50px" src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Perumahan Alam Citra" /> -->
     </div><!--close welcome_slogan-->
   </div><!--close strapline-->   
   <nav>
      <div id="menubar">
        <ul id="nav">
          <li class="current"><a href="<?php echo $this->baseUrl();?>">Home</a></li>
          <li><a href="<?php echo $this->baseUrl();?>/index/about">About Us</a></li>
          <li><a href="#">Ad/Art</a></li>
          <li><a href="#">Struktur</a></li>
          <li><a href="<?php echo $this->baseUrl();?>/index/galery">Galeri</a></li>
          <li><a href="<?php echo $this->baseUrl();?>/index/contactus">Contact Us</a></li>
        </ul>
      </div><!--close menubar-->  
    </nav> 
 </header>
  
  <div class="slideshow">
   <ul class="slideshow">
    <li class="show"><img width="1000" height="300" src="<?php echo $this->baseUrl();?>/images/coca-cola.jpg" alt="Coca-Cola" /></li>
    <li><img width="1000" height="300" src="<?php echo $this->baseUrl();?>/images/alamcitra1.jpg" alt="Tampak Depan Perumahan Alam Citra" /></li>
    <li><img width="1000" height="300" src="<?php echo $this->baseUrl();?>/images/jogja.png" alt="Jogja Istimewa" /></li>
   </ul> 
  </div>

  <div id="site_content">   
    
   <div class="sidebar_container">       
    <div class="sidebar">
      <div class="sidebar_item">
        <h2>News Update</h2>
        <a href="#">Welcoming Address</a>
        <a href="<?php echo $this->baseUrl();?>/agenda">Agenda Warga Alam Citra</a>
        <a href="#">Program Kerja</a>
        <a href="<?php echo $this->baseUrl();?>/laporan">Laporan Keuangan</a>
      </div><!--close sidebar_item--> 
    </div><!--close sidebar-->        
    <div class="sidebar">
      <div class="sidebar_item">
        <h2>Iklan</h2>
        <!-- <h3>February 2013</h3> -->
        <a href="#">Jual Rumah Tipe 42</a>      
        <a href="#">Jual Rumah Tipe 43 [Sold Out]</a>      
        <a href="#">Rumah dikontrakan Tipe 50</a>         
      </div><!--close sidebar_item--> 
    </div><!--close sidebar-->    

  </div><!--close sidebar_container-->  

  
     
    <div id="content">
        <div class="content_item">
      <?php  echo $this->layout()->content;?>
    </div><!--close content_item-->
      </div><!--close content-->   
  </div><!--close site_content-->   

     <script type="text/javascript">
       $(document).ready(function(){
        $("ul#nav li a").live('click', function(){
          //$(this).parent().siblings().find('.current').removeClass('current');
          //$(this).parent('li').addClass('current');
          $(this).parent().removeClass("current");
        });
        $("div.gue").hide();
        $("#tampilgue").live('click', function(){
          $('div.gue').fadeIn('slow');
        });
        $('a.close').click(function(eve){
          eve.preventDefault();
         $(this).parents('div.gue').fadeOut('slow');
        });
      });
    </script>
    <style type="text/css">
      div.gue {
          position: fixed;
          top: 0px;
          bottom: 0px;
          left: 0px;
          right: 0px;
          width: 100%;
          height: 100%;
          background: none repeat scroll 0% 0% rgba(0, 0, 0, 0.8);
          z-index: 9999;

      }
      div#boxgue {
          margin: 5% auto;
          background: none repeat scroll 0% 0% rgba(255, 255, 255, 0.9);
          width: 50%;
          height: 60%;
          box-shadow: 0px 0px 15px #000;
          z-index: 9999;
          border-radius: 15px;
      }
      a.close {
          text-decoration: none;
          color: #000;
          margin: 10px 15px 0px 0px;
          float: right;
          font-family: tahoma;
          font-size: 20px;
      }
      p#tampilgue{
        cursor: pointer;
        margin-top: 5px;
      }
    </style>
    <footer>
    <!-- <a href="index.html">Home</a> | <a href="ourwork.html">Our Work</a> | <a href="testimonials.html">Testimonials</a> | <a href="projects.html">Projects</a> | <a href="contact.html">Contact</a><br/><br/>
    <a href="http://fotogrph.com">Images</a> | Heart Internet <a href="http://www.heartinternet.co.uk/web-hosting/">web hosting</a> | website template by <a href="http://www.freehtml5templates.co.uk">Free HTML5 Templates</a> -->
    <p id="tampilgue">&copy; Alam Citra 2015</p>
    </footer>
  <div class="gue" style="display:none;">
      <div id="boxgue">
        <a class="close" href="#">X</a>
        <img src="<?php echo $this->baseUrl();?>/images/hey.png" width="400px" height="250px" style="margin:0px 20%;"/>
        <p align="center" style="font-weight:600;font-size:19px;padding:0px;">Contact Person : yafiemiftah@gmail.com</p>
        <p align="center" style="font-weight:600;font-size:19px;padding:0px;">hendyivan@gmail.com</p>
        <p align="center" style="font-weight:600;font-size:19px;padding:0px;">No Telp : 085647337473 dan 085725155543</p>
      </div>
  </div><!--close main-->
  
  <!-- javascript at the bottom for fast page loading -->
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/image_slide.js"></script>
  
</body>
</html>