<html>
<script type="text/javascript">
$(function() {
    $( "#tgl-agenda" ).datepicker({ dateFormat: 'yy-mm-dd' }).val();
});
</script>
<div class="panel panel-info">
<div class="panel-heading"><i class="glyphicon glyphicon-dashboard"></i><b>EDIT AGENDA</b></center></div>
</br>
<form class="form-horizontal" role="form" method="post" autocomplete="off" enctype="multipart/form-data">
	<?php 
		if($this->message!=''){ ?>
			<div class="alert alert-danger"><?php echo $this->message;?></div>
	<?php 
		}
	?>
	<?php 
		if($this->msg!=''){ ?>
			<div class="alert alert-success"><?php echo $this->msg;?></div>
	<?php 
		}
	?>
<div style="width:800px;margin-left: auto;margin-right: auto;text-align: left;">
  <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Agenda Title</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="nama" name="nama" value="<?php echo $this->det[0]['agenda_name'];?>">
	      <input type="hidden" class="form-control" id="id" name="id" value="<?php echo $this->det[0]['agenda_id'];?>">
	    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Agenda Detail</label>
     <div class="col-sm-10">
     	<textarea id="tos" name="tos"><?php echo $this->det[0]['agenda_detail'];?></textarea>
						<script type="text/javascript">
							CKEDITOR.replace( 'tos',  {
	allowedContent: true
} );
						</script>
    </div>
  </div>
   <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Agenda Date</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="tgl-agenda" name="tgl-agenda" value="<?php echo $this->det[0]['agenda_date'];?>">
	    </div>
  </div>
   <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Agenda Place</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="place" name="place" value="<?php echo $this->det[0]['agenda_place'];?>">
	    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Save</button>
       <button type="reset" class="btn btn-default" onclick="window.location='<?php echo $this->baseUrl();?>/admin/agenda/index'">Cancel</button>
    </div>
  </div>
</div>
</form>
</div>
</html>